language: ruby
sudo: false
rvm:
  - 2.2
branches:
  only:
    - master
script:
  - bundle exec jekyll build
after_success:
  # https://github.com/travis-ci/travis.rb/issues/239
  - openssl aes-256-cbc -K $encrypted_0679a2e78c39_key -iv $encrypted_0679a2e78c39_iv -in .travis.d/secrets.tar.enc -out .travis.d/secrets.tar -d
  - (cd .travis.d; tar xf secrets.tar;
     chmod 600 rsa;
     mv rsa ~/.ssh/rsa-target;
     mv ssh-config ~/.ssh/config)
  - rsync --delete -ar _site/ target:/A/infocom-nom-17.cs.ucla.edu/
